[tool.poetry]
name = "repo3"
version = "1.0.0"
description = "A repo3 version"
authors = ["Julian Merida <julianmr97@gmail.com>"]
packages = [
    { include = "repo3" },
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"