[tool.poetry]
name = "repo1"
version = "1.0.0"
description = "A repo1 version"
authors = [{name= "Julian Merida",  email="julianmr97@gmail.com"}]

[dependencies]
repo2="1.0.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"