[tool.poetry]
name = "repo1"
version = "1.0.0"
description = "A repo1 version"
authors = ["Julian Merida <julianmr97@gmail.com>"]



[tool.poetry.dependencies]
repo2="1.0.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"